/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bluetune_player_Player */

#ifndef _Included_com_bluetune_player_Player
#define _Included_com_bluetune_player_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bluetune_player_Player
 * Method:    _init
 * Signature: (Lcom/bluetune/player/PlayerListener;)J
 */
JNIEXPORT jlong JNICALL Java_com_bluetune_player_Player__1init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_bluetune_player_Player
 * Method:    _setInput
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_bluetune_player_Player__1setInput
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_bluetune_player_Player
 * Method:    _setOutput
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_bluetune_player_Player__1setOutput
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_bluetune_player_Player
 * Method:    _play
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_bluetune_player_Player__1play
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_bluetune_player_Player
 * Method:    _stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_bluetune_player_Player__1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_bluetune_player_Player
 * Method:    _pause
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_bluetune_player_Player__1pause
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_bluetune_player_Player
 * Method:    _seekToTime
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_bluetune_player_Player__1seekToTime
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_bluetune_player_Player
 * Method:    _seekToTimeStamp
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_bluetune_player_Player__1seekToTimeStamp
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_bluetune_player_Player
 * Method:    _seekToPosition
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_bluetune_player_Player__1seekToPosition
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_bluetune_player_Player
 * Method:    _setVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_bluetune_player_Player__1setVolume
  (JNIEnv *, jclass, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
